name: Update EPG
on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Eseguo filtro
        run: python3 filter_epg.py
      - name: Salvo risultati
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add guida.xml
          git commit -m "Aggiornamento EPG" || exit 0
          git push
